name: Production

on:
  push:
    branches: main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build crm image
        run: |
          cd crm 
          docker build -t crm-app . --no-cache

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Debug: System Info"
        run: |
          whoami
          groups
          hostname
          pwd

      - name: "Debug: Docker"
        run: docker info


      - name: Deploy
        run: |
          docker-compose down --volumes
          docker-compose up -d
